# commond
cookie_secret: JIaCjeGlSsqGUkfjPQNVAHPTGCqhBkxOrboesVT4zGE=

cookie:
  cookie_expire: 864000

mysql:
    host: 42.159.244.119
    port: 3306
    user: david
    password: 2wsx3edc
    dbname: medlogic

mongodb:
  host: 42.159.244.119
  port: 27017
  db: medlogic

email:
  host: smtp.qq.com
  user: 1910593312@qq.com
  password: pwkcfklynwsdcgbe
  to: 1910593312@qq.com
  cc:


# user server
user_server:
    host: localhost
    port: 8000

logger_user:
  level: INFO
  path: logs/user_access.log

# data server
data_server:
  data_file_path_win:  F:/17MedPro/data_file/
  data_file_path: /home/Medlogic/data_file/

logger_data:
  level: INFO
  path: logs/data_access.log

