#user
cookie_secret: JIaCjeGlSsqGUkfjPQNVAHPTGCqhBkxOrboesVT4zGE=

cookie:
  cookie_expire: 864000

mysql:
    host: 42.159.244.119
    port: 3306
    user: david
    password: 2wsx3edc
    dbname: medlogic

user_server:
    host: 42.159.244.119
    port: 8801

email:
  host: smtp.qq.com
  user: 1910593312@qq.com
  password: pwkcfklynwsdcgbe
  to: 1910593312@qq.com
  cc:

logger:
  level: INFO
  path: logs/access.log
