#user
cookie_secret: JIaCjeGlSsqGUkfjPQNVAHPTGCqhBkxOrboesVT4zGE=

mysql:
    host: localhost
    port: 3306
    user: root
    password: root
    dbname: medlogic

user_server:
    host: localhost
    port: 8801

email:
  host: smtp.qq.com
  user: 1910593312@qq.com
  password: pwkcfklynwsdcgbe
  to: 1910593312@qq.com
  cc: