-- 用户表
SET FOREIGN_KEY_CHECKS = 0; -- 禁用外键约束，创建完后恢复
DROP TABLE IF EXISTS tbl_user;
CREATE TABLE tbl_user(
  uid INT NOT NULL AUTO_INCREMENT ,
  account VARCHAR(255) UNIQUE NOT NULL,
  email CHAR(50) UNIQUE NOT NULL,
  password CHAR(50) NOT NULL,
  image VARCHAR(255) DEFAULT NULL ,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(uid)

)ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- cookie 表
DROP TABLE IF EXISTS tbl_cookies;
CREATE TABLE tbl_cookies(
  cookie VARCHAR(255) PRIMARY KEY ,
  value VARCHAR(255) NOT NULL ,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS = 1; -- 恢复外键约束
